"""Explicit preliminary support/retention specification and elementary load screens."""
import json,math
from pathlib import Path
from three_link_fea import OUT,save

def main():
 frozen=json.loads((OUT/'frozen_designs.json').read_text());rows=[]
 for ch,d,L,lt,t,bolt in zip(frozen['channels'],(.02,.04,.08),(.12,.20,.36),(.05,.075,.12),(.005,.008,.012),(4,6,10)):
  x=ch['source_designs'][0];s=x['scale'];fc=ch['config']['carrier_hz'];wmax=math.pi*(fc+3*.08/(.4*(224/162)));m=x['mass_kg'];I=x['inertia_kg_m2'];T=x['peak_torque_nm'];G=200e9/(2*1.3);J=math.pi*d**4/32;EI=200e9*J/2
  # Simplified cylindrical stub-shaft and annular flange inventory; fasteners/collars excluded.
  shaftmass=7850*math.pi*d*d/4*L;R=.03*s;r=.006*s;flangemass=2*7850*math.pi*(R*R-r*r)*t;addedI=shaftmass*d*d/8+flangemass*(R*R+r*r)/2;total=m+shaftmass+flangemass
  ktheta=G*J/lt;tau=16*T/(math.pi*d**3);moment=total*9.80665*L/4;bending=32*moment/(math.pi*d**3);equiv=math.sqrt(bending*bending+3*tau*tau)
  insertmass=2.3938806850273725*s**3;force=insertmass*wmax*wmax*.2*s;area=.07*s*.02*s
  lateral=[]
  for kb in (1e7,1e8,1e9):
   ks=48*EI/L**3;keff=1/(1/ks+1/(2*kb));lateral.append(dict(per_bearing_stiffness_n_m=kb,translational_frequency_hz=math.sqrt(keff/total)/(2*math.pi),static_sag_um=total*9.80665/keff*1e6))
  rows.append(dict(distance_m=x['distance_m'],carrier_hz=fc,shaft_diameter_mm=d*1000,bearing_span_mm=L*1000,drive_torsion_length_mm=lt*1000,flange_thickness_mm=t*1000,flange_od_mm=2*R*1000,pilot_diameter_mm=2*r*1000,flange_bolt_circle_mm=.04*s*1000,flange_bolt_count=6,flange_bolt_nominal_mm=bolt,bolt_shear_load_from_torque_n=T/(6*.02*s),bare_rotor_mass_kg=m,illustrative_central_assembly_mass_kg=shaftmass+flangemass,central_added_polar_inertia_kg_m2=addedI,central_inertia_increase_percent=100*addedI/I,gravity_radial_load_per_support_n=total*9.80665/2,insert_mass_kg=insertmass,max_insert_centrifugal_force_n=force,nominal_insert_projected_pressure_mpa=force/area/1e6,nominal_shaft_vm_mpa=equiv/1e6,nominal_shaft_yield_ratio=650e6/equiv,shaft_torsional_stiffness_nm_rad=ktheta,shaft_only_rotor_torsion_hz=math.sqrt(ktheta/(I+addedI))/(2*math.pi),lateral_sensitivity=lateral))
 save(OUT/'assembly_screen.json',rows)
 lines=['# Preliminary materials and assembly specification','',
 'This is an engineering study concept chosen after the user requested reasonable material and assembly assumptions. It is not a drawing release or a validated contact/rotordynamic assembly. The 3D FEA retains the original bare rotor and idealized boundary conditions; these assembly estimates are separate.', '',
 '## Materials','',
 '- Carrier: unwelded 6061-T651 machined plate; retain E=70 GPa, nu=.33 and density 2700 kg/m^3. Use 240 MPa room-temperature yield for screening, rounded below the 35 ksi minimum listed for the applicable thickness range in [Kaiser sheet/plate data](https://online.kaiseraluminum.com/depot/PublicProductInformation/Document/1010/Kaiser_Aluminum_Sheet_Plate.pdf), p.20. Stock certification and product form must match.',
 '- Inserts: normalized 1045 steel, E=200 GPa, nu=.30, density 7850 kg/m^3, with a specifically ordered and certified minimum yield of 300 MPa. [Atlas 1045](https://atlassteels.com.au/documents/Atlas1045.pdf) distinguishes typical values from guaranteed special-order properties; grade alone is insufficient.',
 '- Shafts and hub flanges: 4140 quenched and tempered, with a conservative specified minimum yield of 650 MPa. [Atlas 4140](https://atlassteels.com.au/documents/Atlas4140.pdf) lists higher minimum proof stress for its relevant supplied condition/diameter. Retain the modeled steel elastic constants for continuity.',
 '- Use a factor of two against the stated room-temperature yield values as an initial static design screen. This is a chosen study criterion, not a code-prescribed safety factor, fatigue allowable or certification.', '',
 '## Arrangement','',
 'Choose a horizontal shaft and vertical rotor plane initially: gravity then acts in the plane and avoids the much larger static axial sag of the thin carrier. Retain both attitudes in the FEA bounds. Straddle the rotor with two bearing supports; use a matched back-to-back angular-contact locating pair on the drive side and an axially floating cylindrical-roller support opposite. This follows the general [SKF locating/non-locating arrangement](https://www.skf.com/binaries/pub12/Images/0901d196802809de-Rolling-bearings---17000_1-EN_tcm_12-121486.pdf). Bearing preload, exact part numbers, stiffness and foundation design are not yet validated.', '',
 'Use two flanged stub shafts piloted into the existing scaled bore and clamped to opposite hub faces. This allows standard 20/40/80 mm bearing seats without enlarging the BER-qualified rotor bore. Six fitted flange bolts carry torque by an explicit positive load path; no friction-only torque credit is taken. Bolt holes and clamping pressure must be added to the assembly contact model. The plain-shaft stress calculation below omits stress concentrations at shoulders/fillets and bolt holes.', '',
 'For each insert, use a machined positive shoulder on one side of the carrier and a removable split retaining collar engaged in a groove on the other. The cylindrical pocket carries radial centrifugal load by contact; shoulder/collar carries axial retention. Do not credit adhesive bonding or uncontrolled interference. Define running clearance, collar/groove dimensions, fastener preload, temperature and tolerances in a dedicated contact submodel before calling this attachment validated. Added off-axis metal/removal for grooves changes source mass and inertia and must be included in a revised finite-volume field calculation.', '',
 '| Link (m) | Bearing-seat diameter (mm) | Bearing span (mm) | Hub flange thickness (mm) | Six flange bolts | Nominal shaft VM (MPa) | Insert radial force (kN each) | Nominal pocket pressure (MPa) |', '|---:|---:|---:|---:|:---|---:|---:|---:|']
 for x in rows:lines.append(f"| {x['distance_m']:g} | {x['shaft_diameter_mm']:g} | {x['bearing_span_mm']:g} | {x['flange_thickness_mm']:g} | M{x['flange_bolt_nominal_mm']} | {x['nominal_shaft_vm_mpa']:.2f} | {x['max_insert_centrifugal_force_n']/1000:.2f} | {x['nominal_insert_projected_pressure_mpa']:.2f} |")
 lines+=['','The support calculation uses a central rotor weight on a simply supported solid circular shaft, M=W*L/4, nominal bending stress 32M/(pi*d^3), torsion 16T/(pi*d^3), and von Mises combination. Stiffness uses 48EI/L^3 in series with two radial bearing springs. The 1e7–1e9 N/m per-bearing sweep is a declared sensitivity range, not catalog stiffness. It gives a translational screen only, not a gyroscopic critical-speed prediction. Shaft torsional stiffness is GJ/L_drive; combining it with carrier torsion and motor/coupling dynamics is required before using fixed-bore modes as assembly modes.','',
 'The central shaft/flange mass inventory is illustrative and excludes bolts, collars, motor coupling and bearings. Its axisymmetric idealization contributes no rotating second harmonic, but its inertia still adds drive demand. The qualified masses refer to the bare source rotor. Real asymmetric features and the off-axis retention hardware require a new field/inertia audit.','']
 (OUT/'ASSEMBLY_SPECIFICATION.md').write_text('\n'.join(lines));print(json.dumps(rows,indent=2))
if __name__=='__main__':main()
