"""Compile latency/cached-filter equivalence diagnostics."""
from pathlib import Path
import json,hashlib
import numpy as np
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'results/fixed_rate_sizing_2026_09_20';OUT=BASE/'decoder_latency_v2'
reference=json.loads((BASE/'efficient_soft_v1/checkpoint_process.json').read_text())[0]
cached=json.loads((OUT/'reference_cached.json').read_text())[0]
error=float(np.max(abs(np.array(reference['llr'])-cached['llr'])))
assert error<1e-7 and reference['bytes']==cached['bytes']
rows=json.loads((OUT/'frame224.json').read_text());largest=np.array(rows[-1]['llr']);summary=[]
for row in rows:
 llr=np.array(row['llr']);summary.append(dict(width=row['width'],decoder_s=row['runtime_s'],airtime_s=row['airtime_with_acquisition_budget_s'],batch_latency_budget_s=row['runtime_s']+row['airtime_with_acquisition_budget_s'],max_llr_difference_to_widest=float(max(abs(llr-largest))),relative_llr_l2=float(np.linalg.norm(llr-largest)/np.linalg.norm(largest)),sign_changes=int(np.count_nonzero(np.signbit(llr)!=np.signbit(largest)))))
result=dict(previous_reference_runtime_s=reference['runtime_s'],cached_reference_runtime_s=cached['runtime_s'],speedup=reference['runtime_s']/cached['runtime_s'],reference_max_llr_difference=error,frame224=summary,source_sha256={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in ('src/gravcomm/causal_sequence.py','src/gravcomm/environmental_noise.py','tests/test_causal_sequence.py','tests/test_environmental_noise.py','scripts/benchmark_checkpoint_soft.py','scripts/profile_causal_decoder.py','scripts/compile_decoder_latency.py')})
(OUT/'compiled.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# Receiver latency and compilation assessment','','## Changes implemented','','Cache the 49 tone-transition waveforms at each receiver sample-clock position and their zero-state SOS-filter responses. Cache the six filter-state impulse responses and state-transition matrix. A path branch is then formed by linear superposition of its inherited filter state and phase-rotated cached waveform. This uses the same causal filter, full noise covariance, and full path history. It introduces roundoff differences, not a truncated impulse response or changed physical model. The samplewise implementation remains available via cached_branches=False for verification. Vectorized Peterson lookup removes 262,144 scalar calls from covariance setup.','','The prior 32-byte profile covered a base search and eight representative continuations. It took 5.736 s with profiling enabled; 3.545 s was charged directly to decode, 0.718 s cumulatively to sosfilt, and approximately 1.05 s to background components. Time charged to decode includes compiled NumPy operations; it must not be interpreted as all Python interpreter overhead. See receiver_profile.txt and .prof.','','## Same-record equivalence and speed','',f"On the identical 40-byte 20 Hz diagnostic with a 512-path, four-process search, runtime changed from {reference['runtime_s']:.2f} to {cached['runtime_s']:.2f} s ({result['speedup']:.2f}x). Maximum uncapped LLR difference was {error:.3g}; hard bytes agree. Runtime includes process startup, snapshots, setup and all competing-bit searches. These are single-host timing observations, not a guaranteed real-time bound.",'','## Shorter frame candidate','','224 useful bits + 16 header bits + 16 CRC bits = 256 mapped bits (32 bytes). These require 96 CF-FSK symbols; add 12 acquisition-budget symbols and six trailing symbols. At Ts=224/114=1.964912 s, budgeted airtime is 224 s and nominal useful rate is 1 bit/s. The diagnostic generates 32 random mapped bytes, rather than constructing a validated header/CRC/acquisition protocol. Twelve acquisition symbols are budgeted but acquisition is assumed known. This is an uncoded receiver diagnostic, not coded throughput qualification.','','The symbol duration is about 3.3% shorter than the prior Ts=256/126 diagnostic, increasing inertial torque by about 6.9% for unchanged q and transition fraction. Mechanical feasibility must be rechecked with the actual Tx; this is not a free reduction in packet length.','','| Beam | Decoder s | Airtime + batch decoding s | Max LLR change vs widest | Relative L2 change | Sign changes |','|---:|---:|---:|---:|---:|---:|']
for row in summary:lines.append(f"| {row['width']} | {row['decoder_s']:.2f} | {row['batch_latency_budget_s']:.2f} | {row['max_llr_difference_to_widest']:.4g} | {row['relative_llr_l2']:.4g} | {row['sign_changes']} |")
lines+=['','This sum credits no overlap of decoding with reception. It includes the acquisition airtime allowance, but successful acquisition, code decoding, measured worst-case runtime and residual startup/processing must still be budgeted. Self-comparison of the widest row is not a convergence proof. One noise record is insufficient for a BER claim.','','The same nine-search profiled workload falls from 5.736 to 2.687 s and from 3,290,875 to 114,795 Python-level calls after optimization. Background evaluation drops from about 1.05 to 0.021 s and cumulative SOS filtering from 0.718 to 0.013 s. The remaining 2.223 s charged to decode includes NumPy operations and copying; use more detailed kernel profiling before predicting a native-port speedup. See receiver_profile_optimized.txt.', '', '## Would C++ or C# help?','','A targeted compiled kernel could reduce path-management overhead, temporary allocations and memory traffic. A whole-language rewrite alone does not guarantee a speedup: NumPy linear algebra already uses BLAS/LAPACK (https://numpy.org/doc/2.0/reference/routines.linalg.html), and SciPy filtering is compiled. The current improvement comes from avoiding repeated work. C++ is a natural option for a small allocation-controlled native kernel exposed to the existing Python validation harness. C# can also provide SIMD and efficient buffer processing (https://learn.microsoft.com/en-us/dotnet/standard/simd), particularly if the deployed receiver application uses .NET, but requires deliberate array layout and native linear-algebra integration. Neither language fixes beam-search approximation or missing acquisition.','','No native implementation speedup is claimed. dotnet is on PATH but dotnet --list-sdks returned no SDK; no C++ compiler was found on PATH in this check. No toolchain was installed. Next profile the optimized implementation before selecting a kernel to port. Preserve samplewise/exhaustive references and compare uncapped likelihoods after every optimization.','','20 relevant tests pass, including cached versus samplewise constrained decoding with nonzero prepacket filter state and sample-clock phase, vectorized versus scalar Peterson spectra, and all prior causal/environmental/sequence checks. No communication-performance statement in the manuscript was updated.']
(OUT/'RESULTS.md').write_text('\n'.join(lines)+'\n');print(json.dumps(result,indent=2))
