"""Compile measured streaming feasibility and approximation checks."""
from pathlib import Path
import json,hashlib
import numpy as np
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results/fixed_rate_sizing_2026_09_20/streaming_soft_v1'
a=json.loads((OUT/'validation.json').read_text());wide=json.loads((OUT/'wide_reference.json').read_text());h5=json.loads((OUT/'history5.json').read_text());independent=json.loads((OUT/'independent_records.json').read_text())
def comparison(x,y):
 x=np.array(x);y=np.array(y);valid=np.isfinite(x)&np.isfinite(y)
 return dict(max_abs_difference=float(max(abs(x[valid]-y[valid]))),relative_l2=float(np.linalg.norm(x[valid]-y[valid])/np.linalg.norm(y[valid])),sign_changes=int(np.count_nonzero(np.signbit(x[valid])!=np.signbit(y[valid]))),finite_bits=int(valid.sum()))
strong=a['runs'][2];weak4=next(x for x in independent if x['nbytes']==32 and x['history_symbols']==4);weak5=next(x for x in independent if x['nbytes']==32 and x['history_symbols']==5);long=next(x for x in independent if x['nbytes']==128)
checks=dict(strong_history4_vs5=comparison(strong['llr'],h5['llr']),weak_history4_vs5=comparison(weak4['llr'],weak5['llr']),persistent_array_bytes_32=weak4['peak_persistent_array_bytes'],persistent_array_bytes_128=long['peak_persistent_array_bytes'])
assert long['peak_persistent_array_bytes']<=1.01*weak4['peak_persistent_array_bytes']
assert all(x['pruned_states']==0 and x['missing_bit_hypotheses']==0 for x in independent)
assert max(x['max_symbol_processing_s'] for x in independent)<1.75
lines=['# Bounded-state streaming soft receiver','','## Implemented architecture','','CompactInnovations uses finite-startup Cholesky coefficients for the first 65 samples, then a fixed 64th-order complex linear predictor. Signal and noise use the same transform. The exact marginal stationary covariance is retained at startup; the later whitening approximation is tested against the aliased physical noise spectrum. Memory and filtering work per block are independent of packet length.','','StreamingSoftReceiver consumes fixed-clock samples incrementally. Each trellis state labels the discrete modulation phase and recent tone history, carrying its own causal SOS filter mean state and 64-sample mean history. At a state merge only the best forward survivor carries its filter history; all incoming retained edges are kept in a fixed-lag max-log graph. This is reduced-state sequence estimation, not exact merging of equal continuous states. That approximation is assessed by increasing recent history and comparing to wider full-history paths. No packet reruns, dense packet covariance, or full-packet graph are used in the streaming decoder.','','The working candidate retains four recent symbols, permits 16,384 states (observed peak 10,878), and uses 12 symbols of lookahead. The graph holds at most 15 symbol layers before emission/removal. No state-budget pruning or missing bit alternatives occurred on the independent diagnostic records. Byte timing, carrier, phase and initial deterministic mean are still acquired inputs. End-of-frame tail information is used and remaining outputs are flushed causally when the last sample arrives.','','## Processing deadlines and bounded storage','','Tests feed each block only when it is available, measuring the complete push call including soft output emission. This is an accelerated input replay, not a hardware real-time scheduler test. The 4 Hz output clock yields blocks of seven or eight samples, separated by 1.75 or 2 s. The nominal symbol duration is 224/114 = 1.964912 s. One Python process and one numerical-library thread were used. Startup model preparation takes about 0.1 s in the primary diagnostic. All measured push times are well below the minimum inter-block interval; the replay therefore predicts no accumulating processing backlog under this workload.','','| Record | History | Peak states | Max block processing (s) | Total compute (s) | Persistent arrays (MB) |','|---|---:|---:|---:|---:|---:|']
lines.append(f"| 32 bytes, 20 Hz, reference amplitude | 4 | {strong['peak_states']} | {strong['max_symbol_processing_s']:.4f} | {strong['total_processing_s']:.3f} | {strong['peak_persistent_array_bytes']/1e6:.2f} |")
for x in independent:lines.append(f"| {x['nbytes']} bytes, 50.3 Hz, amplitude scale {x['scale']:g} | {x['history_symbols']} | {x['peak_states']} | {x['max_symbol_processing_s']:.4f} | {x['total_processing_s']:.3f} | {x['peak_persistent_array_bytes']/1e6:.2f} |")
lines+=['','The 128-byte record is deliberately a long-stream stress test, not a proposed latency-compliant frame. The four-symbol receiver retains the same persistent array storage for 32 and 128 bytes. Reported memory excludes Python object overhead, temporary work arrays, imported libraries and caller-owned input/output storage; it is not peak process RAM. Those other working arrays are also bounded by the configured state budget, history order and block size, not packet length.','','Twelve-symbol lookahead corresponds to 23.58 s after a byte finishes, with sample-grid rounding of at most 0.25 s. This delay overlaps continued reception; it is not an extra complete decoding pass after the frame. The last push includes final traceback/flush and is included in the maximum timing above. No FEC decoder or acquisition algorithm is yet included in the end-to-end latency claim.','','## Whitening validation','','| Predictor order | Maximum whitened PSD error | RMS PSD error |','|---:|---:|---:|']
for x in a['whitening']:lines.append(f"| {x['order']} | {x['max_psd_error']:.4g} | {x['rms_psd_error']:.4g} |")
lines+=['','These figures use the 20 Hz carrier with the specified NHNM/isolation background. The weak-record output additionally saves its own spectral-error check. The 64-sample history corresponds to 16 s of sampled noise memory. Coefficients remain fixed during a record; carrier/background changes require a newly validated model.','','## Soft-output validation and correction of the old reference','','The earlier width-512/1024 packet reference was not converged on four bit alternatives, despite those widths agreeing. A 16,384-path forced-opposite search finds lower-cost physical candidate sequences at all four. The streaming result agrees closely with those widened full-history checks:','','| Bit | Streaming history 4 | Widened forced reference | Absolute difference |','|---:|---:|---:|---:|']
for x in wide:
 if x['width']==16384:
  value=strong['llr'][x['bit']];lines.append(f"| {x['bit']} | {value:.6f} | {x['llr']:.6f} | {abs(value-x['llr']):.4g} |")
lines+=['','These wider paths are stronger references, not a proof of global full-packet optimality. Agreement between two beam widths alone did not certify the previous soft decoder. Do not reuse the old confidence vectors as ground truth.','','History convergence on independent records:','']
for name,value in checks.items():
 if isinstance(value,dict):lines.append(f"- {name}: max absolute change {value['max_abs_difference']:.4g}; relative L2 change {value['relative_l2']:.4g}; {value['sign_changes']} sign changes across {value['finite_bits']} finite bit metrics.")
lines+=['','Doubling the lookahead from 12 to 24 symbols in the strong history-4 case also produced the saved comparison; no missing alternatives occurred. Four streaming unit tests cover exact one-byte likelihoods, exhaustive 65,536-message two-byte graph likelihoods when no state merging is possible, causal chunk/future independence, bounded graph size, and compact whitening/startup. The 20 prior receiver/sequence/environmental tests remain relevant.','','## Outcome and remaining work','','Computational feasibility is demonstrated for these streaming replay cases: fixed persistent storage, bounded measured work per block with substantial deadline margin, and decisions emitted during reception. The expensive full-packet rerun architecture is no longer required for the online prototype. This is not yet post-decoding BER qualification, a hard real-time guarantee, or acquisition validation. Next integrate the emitted max-log outputs with error correction, test more signal levels and modulation settings, and validate post-decoding performance against independent trials. A C++ port is optional optimization at this stage, not a prerequisite for keeping pace in these tests.']
(OUT/'RESULTS.md').write_text('\n'.join(lines)+'\n')
result=dict(status='streaming_replay_feasible_approximation_checks_pass_on_diagnostics_not_BER_qualified',checks=checks,source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in ('src/gravcomm/compact_innovations.py','src/gravcomm/streaming_soft.py','tests/test_streaming_soft.py','scripts/validate_streaming_soft.py','scripts/check_streaming_reference.py','scripts/check_streaming_independent.py','scripts/compile_streaming_soft.py')})
(OUT/'compiled.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
