"""Compile the efficient-soft design audit without treating pilot results as BER evidence."""
import json,hashlib
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'results/fixed_rate_sizing_2026_09_20/efficient_soft_v1'
audit=json.loads((OUT/'validation.json').read_text());groups={}
for name in ('checkpoint_packet.json','checkpoint_refined.json','checkpoint_weak.json','checkpoint_process.json'):
 p=OUT/name
 if p.exists():
  for row in json.loads(p.read_text()):
   key=(row.get('carrier_hz',20.),row.get('scale',1.))
   groups.setdefault(key,[]).append(row)
summary=[]
for (fc,scale),rows in groups.items():
 rows.sort(key=lambda r:r['width']);ref=np.array(rows[-1]['llr'])
 for row in rows:
  llr=np.array(row['llr']);summary.append(dict(carrier_hz=fc,scale=scale,width=row['width'],backend=row.get('backend','thread'),runtime_s=row['runtime_s'],max_llr_difference_to_largest_width=float(max(abs(llr-ref))),relative_llr_l2_to_largest_width=float(np.linalg.norm(llr-ref)/np.linalg.norm(ref)),llr_sign_changes=int(np.count_nonzero(np.signbit(llr)!=np.signbit(ref))),cost=row['cost']))
lines=['# Efficient causal soft-decoder design','','The bit-reservation one-pass beam keeps both bit values but failed accuracy gates. On three exhaustively decoded two-byte diagnostics, small quotas yielded large max-log errors, including sign differences in weak cases. All 24 selected packet forced-opposite searches completed; the largest reduction in an opposite-bit path cost was '+f"{max(x['improvement_in_opposite_cost'] for x in audit['reference_checks']):.3f}."+' Finite outputs and stable hard decisions were insufficient evidence of reliable soft metrics. The one-pass method remains experimental and must not feed code rankings.','','## Working implementation: shared-prefix constrained search','','decode_checkpoint_soft retains byte-boundary snapshots of the ordinary beam. A bit constraint first applies at its byte, so all earlier filtering, phase history, likelihood history and beam pruning are identical and can be reused. The covariance whitening matrix is shared. Four local workers run independent suffix searches (thread and process backends are available); their complete candidate lists are pooled into bit-conditioned minima. This is the same constrained-search approximation as decode_soft, not an additional window or memory truncation. Tests confirm serial and parallel equivalence with the full reruns. The implementation also avoids repeating past-history matrix products for each of seven sibling branches.','','The metric remains causal and exact for every evaluated complete candidate. The search is approximate when beam-pruned. No externally supplied data-bearing rotor trajectory or future noise samples are used. Final soft outputs use the completed packet, and computation time must be added to airtime.','','## Packet benchmark and width sensitivity','','Both diagnostic records are 40 mapped bytes, six tail symbols, Ts=256/126 s, and 256 s observation duration. These are receiver diagnostics, not finalized useful-payload frames. The specified NHNM/isolation background is enabled. Noise seeds and amplitude scales are saved in the benchmark script and JSON. Runtime includes covariance setup, the base pass, all 320 constrained continuations and pooling; four workers and one numerical-library thread per worker. Process runtime includes startup and snapshot transfer.','','| Carrier Hz | Signal scale | Beam width | Backend | Runtime s | Max LLR change vs widest | Relative L2 change | Sign changes |','|---:|---:|---:|---|---:|---:|---:|---:|']
for r in summary:lines.append(f"| {r['carrier_hz']:g} | {r['scale']:g} | {r['width']} | {r['backend']} | {r['runtime_s']:.2f} | {r['max_llr_difference_to_largest_width']:.4g} | {r['relative_llr_l2_to_largest_width']:.4g} | {r['llr_sign_changes']} |")
lines+=['','Zero differences in the widest row are self-comparisons, not independent validation. Width agreement on these individual packets does not establish a BER or universally sufficient search width. Small/no errors on these records are not a reliability estimate. Report uncapped max-log metrics; do not hide disagreement by clipping.','','## Verification and next gate','','18 relevant tests pass: seven sequence tests, seven causal-front-end tests and four environmental tests. They include direct exhaustive likelihoods, prepacket filter state, fractional symbol clocks, constrained search, alternative preservation, and full-rerun versus checkpoint replay with one and two workers. Three short records additionally compare the experimental one-pass search with all 65,536 two-byte hypotheses.','','Width refinement still changes some soft confidences: agreement in hard decisions is not sufficient. Next use measured width convergence to select a computational budget and validate across independent records, signal thresholds, carrier frequencies and code-dependent symbol durations. Shorter-duration weak cases already demonstrate that a narrow beam is not generally reliable. Only validated soft outputs should enter convolutional/LDPC comparisons. The latency limit must include acquisition and actual frame overhead as well as this measured decoder time. No manuscript performance claim is changed.']
lines += ['', 'The width-512 four-process run reproduces the thread metrics exactly and takes 59.40 s on this host. A 256 s record followed by this batch decoding exceeds 300 s. Shorter frames or a validated online bank of both bit-value continuations are needed; no processing overlap is credited yet. Width-dependent soft confidence remains unresolved, so this is a design checkpoint, not an approved production decoder.']
(OUT/'RESULTS.md').write_text('\n'.join(lines)+'\n')
(OUT/'compiled.json').write_text(json.dumps(dict(status='design_audit_not_BER_qualification',packet_width_comparison=summary,source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in ('src/gravcomm/causal_sequence.py','src/gravcomm/causal_receiver.py','src/gravcomm/environmental_noise.py','tests/test_causal_sequence.py','scripts/benchmark_checkpoint_soft.py','scripts/compile_efficient_soft.py')}),indent=2)+'\n')
print(json.dumps(summary,indent=2))
